version: "3.8"

services:
  web:
    build: .
    container_name: web_service
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8010:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: db_service
    volumes:
      - db_volume:/var/lib/postgresql/data/
    ports:
      - 5438:5432
    env_file:
      - .env

volumes:
  db_volume:
    name: db_data_1
  static_volume:
    name: static_data_1
  media_volume:
    name: media_data_1